### ISSUE TITLE
Reload events array

### ISSUE THREAD

**Issue by diegobcorrea** [bm-software/angular-calendar-scheduler#1]
Hi,

I have an issue to detect change on events, I'm making an course schedule and load first time for first course, but when I change course and update events[], the calendar doesnt update.

Any idea?

**Comment by bm-software** [comment]
Hi @diegobcorrea ,
could you give me some steps to exactly reproduce your issue?

**Comment by xavidram** [comment]
Having issues even having the events array populate from a service prior to view rendering. If I change the date using one of the buttons to the next week and then go back, the events array populates on the view, but upon initial load, it does not. Any idea? I try loading the service on init. I do see private functions for reloading the view, but I think i am missing some other way of refreshing the view at least once more prior to view rendering.

**Comment by xavidram** [comment]
https://github.com/bm-software/angular-calendar-scheduler

You can pull this repo down and run it. This is the one I was testing with.

**Comment by bm-software** [comment]
@xavidram I've just updated the library and the sample app, simulating a delayed service call in `app.component` `ngOnInit` method and all seems to be fine.

Could you give it a try a let me know if the problem is solved?

**Comment by bm-software** [comment]
I will close this for inactivity. I suppose it is solved because I still not experiencing this problem :)
