### ISSUE TITLE
aot build error

### ISSUE THREAD

**Issue by DerickBeckwith** [bm-software/angular-calendar-scheduler#2]
When running 'ng build --prod' the cli gives the following error: 

Unexpected value 'undefined' declared by the module 'SchedulerModule in node_modules/angular-calendar-scheduler/angular-calendar-scheduler.d.ts'

**Comment by bm-software** [comment]
@DerickBeckwith I've just released the new version `0.1.9` and it should works fine now. Give it a try :)
