### ISSUE TITLE
Event drag & resize?

### ISSUE THREAD

**Issue by DamirPirija** [bm-software/angular-calendar-scheduler#3]
Hi @bm-software !
Is it possible to drag and resize events?

**Comment by bm-software** [comment]
Hi @DamirPirija ! No for now it's not possible, sorry. In the future I will add that feature. I'm working on that library these days so I'll consider it :)

**Comment by bm-software** [comment]
@DamirPirija I've just release the `1.0.5` component version. I've added drag and resize feature to the component  and many other improvements :)
