### ISSUE TITLE
Milisecond problem in hourSegments events verification

### ISSUE THREAD

**Issue by DaanKrug** [bm-software/angular-calendar-scheduler#7]
If in a schedule we have 4 ( or more than 1) divisions in each hour, 
when add events in same hour, each one in a respective subdivision:
- If add events in top -> bottom direction, it's OK.
- Otherwise if add events from bottom -> top direction, the calculation of number of events on a 
segment result erroneously > 0, and then not is possible add a event in a segment imediately in top.

This issue stay in file angular-calendar-scheduler.js, between lines 374 and 396. Below follows a bit code whit my correction suggestion: 
...
var segments = hour.segments.map(function (segment) {
                segment.date = dateAdapter.setDate(dateAdapter.setMonth(dateAdapter.setYear(segment.date, day.date.getFullYear()), day.date.getMonth()), day.date.getDate());
                /** @type {?} */
                var startOfSegment = segment.date;
                /** @type {?} */
                var endOfSegment = dateAdapter.addMinutes(segment.date, MINUTES_IN_HOUR / hourSegments); 
				// bug correction needed
				if(hourSegments > 1){
					endOfSegment.setTime(endOfSegment.getTime() - 1);
				}
				// end bug correction needed
                /** @type {?} */
                var eventsInSegment = getEventsInPeriod(dateAdapter, {
                    events: eventsInHour,
                    periodStart: startOfSegment,
                    periodEnd: endOfSegment
                });
                return /** @type {?} */ ({
                    segment: segment,
                    date: new Date(segment.date),
                    events: eventsInSegment
                });
            });
...

before:
![bug_before](https://user-images.githubusercontent.com/26380119/53608408-6e6e3300-3ba1-11e9-9ec2-cf35dae50536.png)

after:
![image](https://user-images.githubusercontent.com/26380119/53608444-8e9df200-3ba1-11e9-8d81-87553d788eb7.png)

**Comment by bm-software** [comment]
Hi @DaanKrug , thank you very much for you report and for the fix! I'll update the library within next days :)
